// src/lib/wilayas.ts - Complete 58 Algerian Wilayas and shipping metadata

export interface Wilaya {
  id: string;
  code: string;
  nameAr: string;
  nameFr: string;
  shippingFee: number;
}

export const WILAYAS: Wilaya[] = [
  { id: '1', code: '01', nameAr: 'أدرار', nameFr: 'Adrar', shippingFee: 1200 },
  { id: '2', code: '02', nameAr: 'الشلف', nameFr: 'Chlef', shippingFee: 600 },
  { id: '3', code: '03', nameAr: 'الأغواط', nameFr: 'Laghouat', shippingFee: 800 },
  { id: '4', code: '04', nameAr: 'أم البواقي', nameFr: 'Oum El Bouaghi', shippingFee: 700 },
  { id: '5', code: '05', nameAr: 'باتنة', nameFr: 'Batna', shippingFee: 600 },
  { id: '6', code: '06', nameAr: 'بجاية', nameFr: 'Bejaia', shippingFee: 600 },
  { id: '7', code: '07', nameAr: 'بسكرة', nameFr: 'Biskra', shippingFee: 700 },
  { id: '8', code: '08', nameAr: 'بشار', nameFr: 'Bechar', shippingFee: 1000 },
  { id: '9', code: '09', nameAr: 'البليدة', nameFr: 'Blida', shippingFee: 400 },
  { id: '10', code: '10', nameAr: 'البويرة', nameFr: 'Bouira', shippingFee: 500 },
  { id: '11', code: '11', nameAr: 'تمنراست', nameFr: 'Tamanrasset', shippingFee: 1500 },
  { id: '12', code: '12', nameAr: 'تبسة', nameFr: 'Tebessa', shippingFee: 700 },
  { id: '13', code: '13', nameAr: 'تلمسان', nameFr: 'Tlemcen', shippingFee: 700 },
  { id: '14', code: '14', nameAr: 'تيارت', nameFr: 'Tiaret', shippingFee: 600 },
  { id: '15', code: '15', nameAr: 'تيزي وزو', nameFr: 'Tizi Ouzou', shippingFee: 500 },
  { id: '16', code: '16', nameAr: 'الجزائر العاصمة', nameFr: 'Alger', shippingFee: 350 },
  { id: '17', code: '17', nameAr: 'الجلفة', nameFr: 'Djelfa', shippingFee: 700 },
  { id: '18', code: '18', nameAr: 'جيجل', nameFr: 'Jijel', shippingFee: 600 },
  { id: '19', code: '19', nameAr: 'سطيف', nameFr: 'Setif', shippingFee: 500 },
  { id: '20', code: '20', nameAr: 'سعيدة', nameFr: 'Saida', shippingFee: 700 },
  { id: '21', code: '21', nameAr: 'سكيكدة', nameFr: 'Skikda', shippingFee: 600 },
  { id: '22', code: '22', nameAr: 'سيدي بلعباس', nameFr: 'Sidi Bel Abbes', shippingFee: 700 },
  { id: '23', code: '23', nameAr: 'عنابة', nameFr: 'Annaba', shippingFee: 600 },
  { id: '24', code: '24', nameAr: 'قالمة', nameFr: 'Guelma', shippingFee: 600 },
  { id: '25', code: '25', nameAr: 'قسنطينة', nameFr: 'Constantine', shippingFee: 500 },
  { id: '26', code: '26', nameAr: 'المدية', nameFr: 'Medea', shippingFee: 500 },
  { id: '27', code: '27', nameAr: 'مستغانم', nameFr: 'Mostaganem', shippingFee: 600 },
  { id: '28', code: '28', nameAr: 'المسيلة', nameFr: 'M\'Sila', shippingFee: 600 },
  { id: '29', code: '29', nameAr: 'معسكر', nameFr: 'Mascara', shippingFee: 600 },
  { id: '30', code: '30', nameAr: 'ورقلة', nameFr: 'Ouargla', shippingFee: 800 },
  { id: '31', code: '31', nameAr: 'وهران', nameFr: 'Oran', shippingFee: 500 },
  { id: '32', code: '32', nameAr: 'البيض', nameFr: 'El Bayadh', shippingFee: 800 },
  { id: '33', code: '33', nameAr: 'إليزي', nameFr: 'Illizi', shippingFee: 1500 },
  { id: '34', code: '34', nameAr: 'برج بوعريريج', nameFr: 'Bordj Bou Arreridj', shippingFee: 500 },
  { id: '35', code: '35', nameAr: 'بومرداس', nameFr: 'Boumerdes', shippingFee: 450 },
  { id: '36', code: '36', nameAr: 'الطارف', nameFr: 'El Tarf', shippingFee: 700 },
  { id: '37', code: '37', nameAr: 'تندوف', nameFr: 'Tindouf', shippingFee: 1500 },
  { id: '38', code: '38', nameAr: 'تيسمسيلت', nameFr: 'Tissemsilt', shippingFee: 600 },
  { id: '39', code: '39', nameAr: 'الوادي', nameFr: 'El Oued', shippingFee: 700 },
  { id: '40', code: '40', nameAr: 'خنشلة', nameFr: 'Khenchela', shippingFee: 700 },
  { id: '41', code: '41', nameAr: 'سوق أهراس', nameFr: 'Souk Ahras', shippingFee: 700 },
  { id: '42', code: '42', nameAr: 'تيبازة', nameFr: 'Tipaza', shippingFee: 500 },
  { id: '43', code: '43', nameAr: 'ميلة', nameFr: 'Mila', shippingFee: 600 },
  { id: '44', code: '44', nameAr: 'عين الدفلى', nameFr: 'Ain Defla', shippingFee: 500 },
  { id: '45', code: '45', nameAr: 'النعامة', nameFr: 'Naama', shippingFee: 800 },
  { id: '46', code: '46', nameAr: 'عين تموشنت', nameFr: 'Ain Temouchent', shippingFee: 700 },
  { id: '47', code: '47', nameAr: 'غرداية', nameFr: 'Ghardaia', shippingFee: 800 },
  { id: '48', code: '48', nameAr: 'غليزان', nameFr: 'Relizane', shippingFee: 600 },
  { id: '49', code: '49', nameAr: 'المغير', nameFr: 'El M\'Ghair', shippingFee: 800 },
  { id: '50', code: '50', nameAr: 'المنيعة', nameFr: 'El Meniaa', shippingFee: 900 },
  { id: '51', code: '51', nameAr: 'أولاد جلال', nameFr: 'Ouled Djellal', shippingFee: 800 },
  { id: '52', code: '52', nameAr: 'برج باجي مختار', nameFr: 'Bordj Baji Mokhtar', shippingFee: 1600 },
  { id: '53', code: '53', nameAr: 'بني عباس', nameFr: 'Beni Abbes', shippingFee: 1100 },
  { id: '54', code: '54', nameAr: 'تيميمون', nameFr: 'Timimoun', shippingFee: 1000 },
  { id: '55', code: '55', nameAr: 'تقرت', nameFr: 'Touggourt', shippingFee: 800 },
  { id: '56', code: '56', nameAr: 'جانت', nameFr: 'Djanet', shippingFee: 1600 },
  { id: '57', code: '57', nameAr: 'عين صالح', nameFr: 'In Salah', shippingFee: 1200 },
  { id: '58', code: '58', nameAr: 'عين قزام', nameFr: 'In Guezzam', shippingFee: 1600 }
];
